### START - Update this section with relevant details ###

substitutions:
  device_name: "devicename"
  friendly_name: Name of the device
  board_type: wt32-eth01

  # MQTT Credentials
  mqtt_host: mqtt.host.net
  mqtt_username: usernameToChange
  mqtt_password: passwordToChange
  mqtt_ota_topic: devicename/ota
  mqtt_logs_topic: devicename/logs
  mqtt_ota_firmware_md5: https://photosbarais.ddns.net/firmware/devicename/firmware.md5
  mqtt_ota_firmware: https://photosbarais.ddns.net/firmware/devicename/firmware.bin

  ip: 192.168.1.34
  mask: 255.255.255.0 
  gw: 192.168.1.1
  dns1: 8.8.8.8
  dns2: 1.1.1.1


### END ###

### connection LAN ###
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip: 
    static_ip: ${ip}
    subnet: ${mask}
    gateway: ${gw}
    dns1: ${dns1}
    dns2: ${dns2}


# Enable logging
logger:
  level: ERROR # VERY_VERBOSE, VERBOSE, DEBUG, INFO, WARN, ERROR, NONE
  baud_rate: 115200 # 0 to disable
  hardware_uart: UART0
  on_message:
    level: VERBOSE
    then:
      - mqtt.publish:
          topic: ${mqtt_logs_topic}
          payload: !lambda |-
            return "Triggered on_message with level " + to_string(level) + ", tag " + tag + " and message " + message;

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}

mqtt:
  broker: ${mqtt_host}
  username: ${mqtt_username}
  password: ${mqtt_password}
  on_message:
    topic: ${mqtt_ota_topic}
    qos: 1
    then:
      - ota.http_request.flash:
          md5_url: ${mqtt_ota_firmware_md5}
          url: ${mqtt_ota_firmware}
      - logger.log: "This message should be not displayed because the device reboots"



http_request:
  verify_ssl: false 

ota:
  - platform: http_request

# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"

