
### START - Update this section with relevant details ###

substitutions:

  device_name: solarpanel
  device_id: "\"solarpanel\""
  friendly_name: Solar Panel
  board_type: wt32-eth01

  # MQTT Credentials
  mqtt_host: mqtt.host.net
  mqtt_username: mqtt
  mqtt_password: mqtt
  mqttstate_topic: solarpanel/test/solarpanel/state

  mqtt_ota_topic: solarpaneltest/ota
  mqtt_logs_topic: solarpaneltest/logs
  mqtt_ota_firmware_md5: https://photosbarais.ddns.net/firmware/test/firmware.md5
  mqtt_ota_firmware: https://photosbarais.ddns.net/firmware/test/firmware.bin


  #network paramerters
  ip: 192.168.1.34
  mask: 255.255.255.0 
  gw: 192.168.1.1
  dns1: 8.8.8.8
  dns2: 1.1.1.1
### END ###

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: ${board_type}
  framework:
    type: esp-idf

### connection LAN ###
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

  manual_ip: 
    static_ip: ${ip}
    subnet: ${mask}
    gateway: ${gw}
    dns1: ${dns1}
    dns2: ${dns2}

# wifi:
#   ssid: SSIDNAME
#   password: SSIDPASSWORD


# Enable logging
logger:
  level: ERROR # VERY_VERBOSE, VERBOSE, DEBUG, INFO, WARN, ERROR, NONE
  baud_rate: 115200
  hardware_uart: UART0
  on_message:
    level: ERROR
    then:
      - mqtt.publish:
          topic: ${mqtt_logs_topic}
          payload: !lambda |-
            return "Triggered on_message with level " + to_string(level) + ", tag " + tag + " and message " + message;


mqtt:
  broker: ${mqtt_host}
  username: ${mqtt_username}
  password: ${mqtt_password}
  on_message:
    topic: ${mqtt_ota_topic}
    qos: 1
    then:
      - ota.http_request.flash:
          md5_url: ${mqtt_ota_firmware_md5}
          url: ${mqtt_ota_firmware}
      - logger.log: "This message should be not displayed because the device reboots"

uart:
  baud_rate: 9600
  id: resol
#  tx_pin: GPIO17
  rx_pin: GPIO05
  debug:

vbus:
  uart_id: resol


http_request:
  verify_ssl: false 

ota:
  - platform: http_request

# Restart & Safe Mode Buttons
button:
  - platform: restart
    name: "Restart Device"

sensor:
  - platform: vbus
    id: vbus1
    model: custom
    dest: 0x10
    source: 0x1117
    command: 0x100
    sensors:
      - id: temp1
        state_topic: null
        name: Temperature 1
        state_class: measurement
        unit_of_measurement: "째C"
        lambda: return ((x[1] << 8) + x[0]) * 0.1f;  // Temperatur
        filters:
#          - throttle_average: 15s
          - sliding_window_moving_average:
              window_size: 30
              send_every: 30
              send_first_at: 2
      - id: temp2
        state_topic: null
        name: Temperature 2
        state_class: measurement
        unit_of_measurement: "째C"
        lambda: return ((x[3] << 8) + x[2]) * 0.1f;  // Temperatur
        filters:
          - sliding_window_moving_average:
              window_size: 30
              send_every: 30
              send_first_at: 2
      - id: temp3
        state_topic: null
        name: Temperature 3
        state_class: measurement
        unit_of_measurement: "째C"
        lambda: return ((x[5] << 8) + x[4]) * 0.1f;  // Temperatur
        filters:
          - sliding_window_moving_average:
              window_size: 30
              send_every: 30
              send_first_at: 2
      - id: temp4
        state_topic: null
        name: Temperature 4
        state_class: measurement
        unit_of_measurement: "째C"
        lambda: return ((x[7] << 8) + x[6]) * 0.1f;  // Temperatur
        filters:
          - sliding_window_moving_average:
              window_size: 30
              send_every: 30
              send_first_at: 2
      - id: pump1
        state_topic: null
        name: Pump 1
        state_class: measurement
        unit_of_measurement: "%"
        lambda: return (x[8]) ;  // Pompe 1
        filters:
          - sliding_window_moving_average:
              window_size: 30
              send_every: 30
              send_first_at: 2
      - id: energy
        filters:
          - sliding_window_moving_average:
              window_size: 30
              send_every: 30
              send_first_at: 3
        state_topic: null
        name: energy
        state_class: measurement
        unit_of_measurement: "wh"
        lambda: return ((x[31] << 24) + (x[30] << 16) + (x[29] << 8) + x[28]);  // Energy produite
        on_value:
          then:
            mqtt.publish_json:
              qos: 1
              retain: true        
              topic: ${mqttstate_topic}
              payload: |-
                root["device_id"] = ${device_id};
                root["energy"] = id(energy).state;  
                root["temp1"] = id(temp1).state;
                root["temp2"] = id(temp2).state;
                root["temp3"] = id(temp3).state;
                root["temp4"] = id(temp4).state;
                root["pump1"] = id(pump1).state;


